# Model config
EMBEDDING_SIZE=384
BATCH_SIZE=32
BLOCK_SIZE=128
STEPS=500
LEARNING_RATE=1e-5
HEAD_COUNT=6
LAYER_COUNT=6
DROPOUT=0.2

# Tokenizer Config
TOKENIZER_NAME="tiktoken"
TOKENIZER_MODEL="o200k_base"

# Data Config
TRAIN_DATA_PATH="data/openwebtext/test.hf"